name: beacons_plugin
description: This plugin makes it easier to scan nearby iBeacons and range them in flutter app. Scaned beacons will provide proximity values.
version: 2.0.8
homepage: https://github.com/umair13adil/simple_beacons_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  beacons: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter 

flutter:
  plugin:
    platforms:
      android:
        package: com.umair.beacons_plugin
        pluginClass: BeaconsPlugin
      ios:
        pluginClass: BeaconsPlugin
